### ISSUE TITLE
Add support for defaulting datetime fields to UTC

### ISSUE THREAD

**Issue by mikeycooper** [dradovic/MigSharp#37]
We often default our datetime fields to the current date in UTC format (GETUTCDATE()) rather than the server's timezone.  This is especially useful for apps used by users in multiple timezones.  We'd love to see support in the official MigSharp for this.  I know it's possible in Oracle using SYS_EXTRACT_UTC(SYSTIMESTAMP), but I don't know enough about Oracle to test it myself.

**Comment by dradovic** [comment]
Available in 3.1.0.
