### ISSUE TITLE
SpecialDefaultValue Guid/NewId

### ISSUE THREAD

**Issue by anishpateluk** [dradovic/MigSharp#51]
It would be nice to set the default value for a GUID field to (newid()) to have the database generate the Guid for uniqueidentifier data type fields.

We use Guids as Ids in our database and let the database generate the Ids.

**Comment by dradovic** [comment]
Feel free to issue a PR for this.

**Comment by anishpateluk** [comment]
Will do buddy

**Comment by dradovic** [comment]
Released in 3.1.2. Added support for sequential GUIDs as well.
