### ISSUE TITLE
Allow Extension of Existing Providers

### ISSUE THREAD

**Issue by jedijohn** [dradovic/MigSharp#54]
I had a case where I wanted to customize the functionality of a single method of one of the providers.  Since the class is marked internal it is not possible to override a single method.  Also, since the helpers are also internal we couldn't just copy the code for that one provider & customize it.

So I'd like to request that the providers be made public and that the methods be marked virtual to allow for extension.

**Comment by dradovic** [comment]
Closing this issue for now as there has not been any traction.

**Comment by jedijohn** [comment]
I ended up modifying the source on my own to get this to work.  Thanks for
at least considering the idea for your project.
