### ISSUE TITLE
NuGet Version 2.3.2

### ISSUE THREAD

**Issue by mediocreguy** [dradovic/MigSharp#59]
Thanks for releasing the new version!  But, unless I'm looking at something wrong (and that is entirely possible), the 2.3.2 NuGet release still contains the 2.3.1 version of the MigSharp.dll - Generate.exe and Migrate.exe are at 2.3.2.

**Comment by dradovic** [comment]
You're right. This is horrible. I have no idea how this happened. I checked it twice. Will fix ASAP.

**Comment by dradovic** [comment]
I've just released 2.3.3 with hopefully the correct assembly versions. Thanks for noticing and reporting.

**Comment by mediocreguy** [comment]
Looks good - Thanks for the quick response!
