### ISSUE TITLE
Specifying a default constraint of type bool on a DbType.Boolean column causes error

### ISSUE THREAD

**Issue by Zouters** [dradovic/MigSharp#61]
Attempting to execute a migration containing the following:

    db.CreateTable("MyTable")
         .WithNotNullableColumn("IsActive", DbType.Boolean).HavingDefault<bool>(true);

Causes the following error:

    MigSharp.General Error: 0 : An error occurred: The name "True" is not permitted in this context.
    Valid expressions are constants, constant expressions, and (in some contexts) variables. Column names are not permitted.
    CREATE TABLE [dbo].[MyTable](
	[IsActive] [bit] NOT NULL CONSTRAINT [MyTable_IsActive_DF]  DEFAULT True;
    )

Of course, it's easy to fix it by just using `HavingDefault<int>(1)` but I think it would be better for it to convert true/false to 1/0 automatically.

**Comment by dradovic** [comment]
I'll have a look into this.

**Comment by dradovic** [comment]
Fix released in 2.3.4.
