### ISSUE TITLE
MigSharp NuGet dependencies

### ISSUE THREAD

**Issue by akabigbro** [dradovic/MigSharp#63]
I have created an empty Visual Studio C# project of which I wish to use MigSharp. Unfortunately I receive an error stating that the package does not contain any assembly references or content files that are compatible.

What are the required dependencies for MigSharp using NuGet?

**Comment by dradovic** [comment]
Which VS version are you using and what is the .NET target framework of your project?

**Comment by akabigbro** [comment]
Visual Studio 2013
.NET Target= 4.0

**Comment by dradovic** [comment]
Mig# 3.x targets .NET 4.5. Mig# 2.x targets .NET 3.5 + 4.0. So, either switch to .NET 4.5 or if you can't use Mig# 2.x.
